# A simple Makefile for CPSC 350
# Assumes the following directory hierarchy:
# Assignment 1
#include <iostream>
#include <fstream>
#include <math.h>
#define _USE_MATH_DEFINES
#include <string>
//brings in type ostringstream.
#include <sstream>
//IO that helps characters
#include <ctype.h>


EXECUTABLE := assignment1

SOURCES := DNAAssignment.cpp

#stuff you don't need to worry about
INCLUDES := -I ../include
EXT := exe
CC := g++

all:
	$(CC) $(INCLUDES) $(SOURCES) -o $(EXECUTABLE).$(EXT)

realclean:
	find . -type f -name "*.o" -exec rm '{}' \;
	find . -type f -name "*.exe" -exec rm '{}' \;

# this line required by make - don't delete
